### ISSUE TITLE
Delete instead of setting to undefined (blocked by lint rule)

### ISSUE THREAD

**Issue by seveibar** [seamapi/fake-seam-connect#83]
Can this be deleted from the object instead of set undefined? Maybe not so important if when it is serialized that happens anyway

_Originally posted by @razor-x in https://github.com/seamapi/fake-seam-connect/pull/81#discussion_r1348352859_

**Comment by razor-x** [comment]
Maybe disable this for fakes, or just disable as needed. I think it is a good rule in general because it guides people to use better patterns overall. The JSON serialization issue is fairly unique to [zustand](https://github.com/pmndrs/zustand/issues/618). A zustand plugin to handling map / set serialization would be loved by the community I'm sure (maybe auto-detect based on initial DB state).

https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-dynamic-delete.md
